apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: 
      selector:
        matchLabels:
          autodeploy: true
  template:
    metadata:
      name: '{{.name}}-nginx' # 'name' field of the Secret
    spec:
      project: "default"
      sources: 
      - repoURL: 'https://charts.bitnami.com/bitnami'
        chart: nginx
        targetRevision: 15.12.2
        helm:
          valueFiles:
          - $values/nginx/values.yaml
      - repoURL: 'https://github.com/puttappa-raghavendra/argocd-apps.git'
        targetRevision: main
        ref: values
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2